# Generated by Django 4.2.30 on 2026-06-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='course',
            name='order',
        ),
        migrations.AddField(
            model_name='course',
            name='agreement_file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
