# Generated by Django 4.2.30 on 2026-06-11 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_course_options_remove_course_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='agreement_file',
        ),
    ]
