# Generated by Django 4.2.30 on 2026-06-15 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_course_agreement_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teacher_email',
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_teacher': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='core.user'),
        ),
        migrations.AddField(
            model_name='tokenpurchase',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tokenpurchase',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tokenpurchase',
            name='processed_expiry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tokenpurchase',
            name='tokens_remaining',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='card_expiry',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='user',
            name='card_number',
            field=models.CharField(blank=True, max_length=19),
        ),
        migrations.AddField(
            model_name='user',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='tokens_earned',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='token_cost',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='lessonaccess',
            name='tokens_spent',
            field=models.IntegerField(default=10),
        ),
        migrations.CreateModel(
            name='TeacherWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens_withdrawn', models.IntegerField()),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=8)),
                ('card_number', models.CharField(max_length=19)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='PaymeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=255, unique=True)),
                ('amount', models.BigIntegerField()),
                ('state', models.IntegerField(default=1)),
                ('create_time', models.BigIntegerField(default=0)),
                ('perform_time', models.BigIntegerField(default=0)),
                ('cancel_time', models.BigIntegerField(default=0)),
                ('reason', models.IntegerField(blank=True, null=True)),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tokenpurchase')),
            ],
        ),
    ]
